name: Deploy Static
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install --frozen-lockfile
      - run: pnpm generate
      - uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist
          github_token: \${{ secrets.GITHUB_TOKEN }}
