name: Storybook Preview
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm storybook:build
      - uses: actions/upload-artifact@v3
        with:
          path: storybook-static
